---
- name: php role
  tags: [role-php]
  block:

  # install
  - ansible.builtin.import_tasks: php-install.yml

  # config
  - ansible.builtin.import_tasks: php-config.yml

  # systemd
  - ansible.builtin.import_tasks: php-systemd.yml