---
- name: php role
  tags:
    - php
  block:

  # install
  - name: Install packages {{ php_install_packages }}
    notify: Reload php-fpm
    ansible.builtin.package:
      name: "{{ php_install_packages }}"
      state: present
      use: auto

  # config
  - ansible.builtin.import_tasks: config.yml

  # systemd
  - ansible.builtin.import_tasks: systemd.yml