---
- tags: [role-php-install]
  block:

  # install
  - name: Install packages {{ php_install_packages }}
    ansible.builtin.package:
      name: "{{ php_install_packages }}"
      state: present
      use: auto
    notify: Reload php-fpm