opcache.enable=1
opcache.max_accelerated_files=7000
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1
; https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html#revalidation
; https://www.scalingphpbook.com/blog/2014/02/14/best-zend-opcache-settings.html
opcache.revalidate_freq=0
opcache.validate_timestamps=0
; https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html#comments
opcache.save_comments=1
; https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html#jit
opcache.jit = 1255
opcache.jit_buffer_size = 8M